<a href="https://colab.research.google.com/github/Estabnzm/Curso_de_Programacion/blob/main/PROYECTO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**BASE DE DATOS**
##Precio cierre mensual por fechas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [69]:
import pandas as pd

url = "https://drive.google.com/uc?export=download&id=1SzEHZlD1SomHSKFBaWlekyTHgJSBq3Gz"
df = pd.read_excel(url)

df.head()

,Date,PFBCOLO,BCOLO,ECOPETL,ISA,GEB,CEMARGOS,GRUPOARG,PFGRUPSU,PFGRUPOA,...,CORFICOL,GRUPOBOL,PROMIG,BOGOTA,MINEROS,TERPEL,PFCORCOL,CNEC,ETB,COLCAP
0,2010-01-29,21760,22200,2455,12680,1198.0,6495.366,19980,NaN,NaN,...,10950.195,40000,4292.245,31473.509,5500,NaN,11264.812,NaN,1140.0,1363.67
1,2010-02-26,22220,22300,2560,12880,1234.0,6506.432,19300,NaN,NaN,...,12686.790,40000,4172.684,34898.567,5550,NaN,12330.403,NaN,1005.0,1391.02
2,2010-03-31,22280,22280,2700,12800,1250.0,6628.151,19800,NaN,NaN,...,13800.060,42500,4182.249,34528.290,5720,NaN,13540.856,NaN,1040.0,1440.58
3,2010-04-30,23000,23020,2765,12980,1290.0,6373.647,19400,NaN,NaN,...,14906.857,40600,4208.552,36842.519,5720,NaN,14579.233,NaN,1155.0,1467.26
4,2010-05-31,23500,23500,2700,12720,1275.4,6218.732,19200,NaN,NaN,...,14468.126,41420,4184.640,35916.827,5700,NaN,14159.686,NaN,1075.0,1444.54

#**EXPLORACIÓN BASE DE DATOS**

In [70]:
# Información dataframe
df.head()

,Date,PFBCOLO,BCOLO,ECOPETL,ISA,GEB,CEMARGOS,GRUPOARG,PFGRUPSU,PFGRUPOA,...,CORFICOL,GRUPOBOL,PROMIG,BOGOTA,MINEROS,TERPEL,PFCORCOL,CNEC,ETB,COLCAP
0,2010-01-29,21760,22200,2455,12680,1198.0,6495.366,19980,NaN,NaN,...,10950.195,40000,4292.245,31473.509,5500,NaN,11264.812,NaN,1140.0,1363.67
1,2010-02-26,22220,22300,2560,12880,1234.0,6506.432,19300,NaN,NaN,...,12686.790,40000,4172.684,34898.567,5550,NaN,12330.403,NaN,1005.0,1391.02
2,2010-03-31,22280,22280,2700,12800,1250.0,6628.151,19800,NaN,NaN,...,13800.060,42500,4182.249,34528.290,5720,NaN,13540.856,NaN,1040.0,1440.58
3,2010-04-30,23000,23020,2765,12980,1290.0,6373.647,19400,NaN,NaN,...,14906.857,40600,4208.552,36842.519,5720,NaN,14579.233,NaN,1155.0,1467.26
4,2010-05-31,23500,23500,2700,12720,1275.4,6218.732,19200,NaN,NaN,...,14468.126,41420,4184.640,35916.827,5700,NaN,14159.686,NaN,1075.0,1444.54

#**Análisis estadístico base de datos**

In [71]:
df.describe(include='all')

,Date,PFBCOLO,BCOLO,ECOPETL,ISA,GEB,CEMARGOS,GRUPOARG,PFGRUPSU,PFGRUPOA,...,CORFICOL,GRUPOBOL,PROMIG,BOGOTA,MINEROS,TERPEL,PFCORCOL,CNEC,ETB,COLCAP
count,182,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,182.000000,159.000000,153.000000,...,182.000000,182.000000,182.000000,182.000000,182.000000,127.000000,182.000000,176.000000,182.000000,182.000000
mean,2017-08-14 18:35:36.263736320,30182.362637,30260.769231,2823.769231,14163.681319,1865.184615,7726.798621,16957.142857,29077.358491,14433.660131,...,20048.741165,56295.824176,5465.713484,52870.994434,3376.857143,10350.393701,17530.535692,49677.784091,390.683516,1457.988956
min,2010-01-29 00:00:00,21600.000000,20980.000000,1030.000000,6640.000000,995.000000,2902.000000,8060.000000,9600.000000,5370.000000,...,10500.000000,39700.000000,2989.029000,24480.000000,1445.000000,6550.000000,10000.000000,9080.000000,59.000000,1076.120000
25%,2013-11-07 06:00:00,27085.000000,26400.000000,2056.250000,9825.000000,1562.500000,6030.621000,14550.000000,19910.000000,9420.000000,...,17154.153250,50905.000000,4275.561250,46024.858250,2300.000000,8010.000000,14892.311000,34947.500000,200.250000,1309.460000
50%,2017-08-15 12:00:00,29100.000000,28850.000000,2644.000000,13440.000000,1815.000000,7565.000000,17910.000000,33040.000000,15400.000000,...,19682.987500,53010.000000,5225.000000,55466.650000,3065.000000,9800.000000,17853.531000,47550.000000,398.500000,1446.120000
75%,2021-05-23 06:00:00,32365.000000,33370.000000,3515.000000,18175.000000,2183.750000,9800.000000,19875.000000,37510.000000,18600.000000,...,23950.111000,61740.000000,6988.750000,63388.406750,4089.000000,11750.000000,20739.440500,53850.000000,543.750000,1623.430000
max,2025-02-28 00:00:00,45800.000000,45700.000000,5700.000000,25700.000000,2875.000000,11960.000000,23780.000000,43600.000000,23400.000000,...,27945.577000,93000.000000,8400.000000,82758.287000,7860.000000,18400.000000,23799.157000,165000.000000,1155.000000,1901.830000
std,NaN,4961.679499,5490.538468,1129.984634,4831.765765,446.272582,2524.409909,3933.681281,9471.721834,5132.165434,...,4433.260967,10124.332766,1491.777579,13958.328410,1445.818750,2847.671118,3470.198655,27595.238076,237.917414,202.029791

#**CÁLCULO RENTABILIDAD MENSUAL x AÑO**

In [72]:
# Rentabilidad mensual usando la fórmula: (mes actual - mes anterior) / mes anterior

rentabilidad = (df - df.shift(1)) / df.shift(1)
print(rentabilidad)

TypeError: cannot perform __rtruediv__ with this index type: DatetimeArray

#**NUEVO ARCHIVO DE RENTABILIDADES**

In [73]:
rentabilidad

,PFBCOLO,BCOLO,ECOPETL,ISA,GEB,CEMARGOS,GRUPOARG,PFGRUPSU,PFGRUPOA,PEI,...,CORFICOL,GRUPOBOL,PROMIG,BOGOTA,MINEROS,TERPEL,PFCORCOL,CNEC,ETB,COLCAP
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.021140,0.004505,0.042770,0.015773,0.030050,0.001704,-0.034034,NaN,NaN,NaN,...,0.158590,0.000000,-0.027855,0.108824,0.009091,NaN,0.094595,NaN,-0.118421,0.020056
2,0.002700,-0.000897,0.054688,-0.006211,0.012966,0.018707,0.025907,NaN,NaN,NaN,...,0.087750,0.062500,0.002292,-0.010610,0.030631,NaN,0.098168,NaN,0.034826,0.035629
3,0.032316,0.033214,0.024074,0.014063,0.032000,-0.038397,-0.020202,NaN,NaN,NaN,...,0.080202,-0.044706,0.006289,0.067024,0.000000,NaN,0.076685,NaN,0.110577,0.018520
4,0.021739,0.020851,-0.023508,-0.020031,-0.011318,-0.024306,-0.010309,NaN,NaN,NaN,...,-0.029431,0.020197,-0.005682,-0.025126,-0.003497,NaN,-0.028777,NaN,-0.069264,-0.015485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,0.067511,0.043046,-0.095745,0.029274,0.020161,0.145333,0.102273,0.093133,0.098976,-0.027643,...,0.216129,-0.039003,0.000000,0.013709,0.038352,0.042000,0.230769,-0.163904,0.000000,0.038904
178,0.015810,0.020635,0.058824,-0.044369,0.019763,0.119907,0.031959,0.003442,0.086957,0.015533,...,0.021220,0.004657,0.000000,-0.022064,0.154583,0.074856,0.015625,0.330396,-0.075000,0.024785
179,-0.022235,-0.025402,-0.069444,-0.005952,-0.054264,0.060291,0.028971,0.115780,0.102857,0.009812,...,-0.046753,0.000000,-0.032468,-0.022562,0.008294,0.026786,-0.001399,-0.081126,0.000000,-0.009015
180,0.176805,0.146277,0.170149,0.106587,0.106557,0.013725,-0.033010,0.100692,-0.034974,0.014576,...,0.197548,0.026490,-0.051007,0.098287,0.145711,0.043478,0.095238,0.018018,-0.081081,0.103046
181,0.036232,0.060325,0.051020,0.121212,0.064815,-0.032882,0.014056,0.344274,0.040268,-0.039718,...,0.035267,0.147419,-0.052334,-0.003390,0.097436,0.008333,0.086957,-0.030088,-0.132353,0.056403

#**RENTABILIDAD PROMEDIO MENSUAL PARA CADA ACCIÓN**

In [75]:
# Calcular rentabilidad promedio por acción (columna)
promedio_por_accion = rentabilidad.mean(axis=0, skipna=True)

# Mostrar resultado
print(promedio_por_accion)

PFBCOLO      0.006246
BCOLO        0.006887
ECOPETL      0.003126
ISA          0.005021
GEB          0.006498
CEMARGOS     0.006521
GRUPOARG     0.002916
PFGRUPSU     0.005072
PFGRUPOA     0.002837
PEI          0.017076
PFAVAL      -0.001548
GRUPOSUR     0.005971
PFDAVVND     0.002047
CELSIA       0.000186
CORFICOL     0.005735
GRUPOBOL     0.005348
PROMIG       0.005049
BOGOTA       0.002558
MINEROS      0.003436
TERPEL      -0.000894
PFCORCOL     0.005022
CNEC        -0.005893
ETB         -0.012609
COLCAP       0.002220
dtype: float64

#**NUEVO ARCHIVO DE PROMEDIO MESUAL**

In [76]:
promedio_por_accion.to_excel('promedio_por_accion', header=['Promedio'])

ValueError: No engine for filetype: ''

#**RENTABILIDAD MÍNIMA DE LAS ACCIONES**

In [78]:
# Rentabilidad mínima de las acciones

rentabilidad_minima = rentabilidad.min().min()

print(f"Rentabilidad mínima observada: {rentabilidad_minima:.4f}")

Rentabilidad mínima observada: -0.3881

#**ACCIÓN CON LA RENATABILIDAD MÁS BAJA**

In [ ]:
# Ubicar la posición (fecha y acción) de la rentabilidad mínima

min_location = rentabilidad.stack().idxmin()
min_value = rentabilidad.min().min()

print(f"La rentabilidad mínima observada fue de {min_value:.4f}, en {min_location[0].date()} para la acción {min_location[1]}")

#**RENTABILIDAD MÁXIMA DE LAS ACCIONES**

In [ ]:
# Rentabilidad máxima de las acciones

rentabilidad_max = rentabilidad.max().max()

print(f"Rentabilidad maxima observada: {rentabilidad_max:.4f}")

#**ACCIÓN CON MAYOR RENTABILIDAD**

In [ ]:
# Ubicar la posición (fecha y acción) de la rentabilidad máxima

max_location = rentabilidad.stack().idxmax()
max_value = rentabilidad.max().max()

print(f"La rentabilidad máxima observada fue de {max_value:.4f}, en {max_location[0].date()} para la acción {max_location[1]}")

#**RENTABILIDAD ACUMULADA TOTAL**

In [ ]:

# Calcular rentabilidad acumulada

precio_inicial = df.iloc[0]  # Primer precio de cada acción
precio_final = df.iloc[-1]   # Último precio de cada acción

# Aplicar la fórmula de rentabilidad acumulada: ((precio final / precio inicial) - 1) * 100

rentabilidad_acumulada = ((precio_final / precio_inicial) - 1) * 100

# Mostrar rentabilidad acumulada por acción

print(rentabilidad_acumulada)

In [ ]:
print(rentabilidad_acumulada)